# Generated by Django 3.2.6 on 2021-08-25 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('xpcs_index', '0001_initial'), ('xpcs_index', '0002_auto_20200626_1852'), ('xpcs_index', '0003_concierge_app_v2'), ('xpcs_index', '0004_filenamefilter'), ('xpcs_index', '0005_remove_reprocessingtask_options_cache')]

    initial = True

    dependencies = [
        ('concierge_app', '0003_concierge_app_v2'),
        ('concierge_app', '0002_mdf_publish_and_search_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilenameFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReprocessingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate_app.action')),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge_app.manifest')),
            ],
        ),
    ]
