# Generated by Django 4.2.7 on 2023-11-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("xpcs_index", "0001_squashed_0005_remove_reprocessingtask_options_cache"),
        ("xpcs_index", "0006_alter_filenamefilter_id_delete_reprocessingtask"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilenameFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regex", models.CharField(max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
