# Generated by Django 2.1.15 on 2020-06-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automate_app', '0001_initial'),
        ('concierge_app', '0002_mdf_publish_and_search_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprocessingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('options_cache', models.TextField()),
                ('action', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='automate_app.Action'
                )),
                ('bag', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='concierge_app.Bag'
                )),
            ],
        ),
    ]
