# Generated by Django 2.1.15 on 2020-06-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpcs_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprocessingtask',
            name='options_cache',
            field=models.TextField(blank=True),
        ),
    ]
