# Generated by Django 2.1.15 on 2020-09-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge_app', '0003_concierge_app_v2'),
        ('xpcs_index', '0002_auto_20200626_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reprocessingtask',
            name='bag',
        ),
        migrations.AddField(
            model_name='reprocessingtask',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge_app.Manifest'),
        ),
    ]
