# Generated by Django 3.1.7 on 2021-03-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpcs_index', '0004_filenamefilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reprocessingtask',
            name='options_cache',
        ),
    ]
