# Generated by Django 4.2.7 on 2023-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    NOTE: THIS SHOULD BE REMOVED ONCE "0001_new_2023_11_16_initial_xpcs_migration.py" IS APPLIED ACROSS ALL
    DEPLOYMENTS.
    """
    dependencies = [
        ("xpcs_index", "0001_squashed_0005_remove_reprocessingtask_options_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filenamefilter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="ReprocessingTask",
        ),
    ]
