from gladier import GladierBaseTool

class BoostCorrRuntime(GladierBaseTool):
    """
    This simple tool fetches the output metadata generated by the Boost Corr tool, and sticks
    it in a place where it can be published alongside other general metadata.
    """

    flow_definition = {
        "StartAt": "BoostCorrRuntime",
        "States": {
            "BoostCorrRuntime": {
                "Type": "ExpressionEval",
                "Parameters": {
                    "tools.$": "$.XpcsBoostCorr.details.results[0].output.metadata.tools",
                },
                "ResultPath": "$.input.corr_timing_output",
                "End": True
                }
        }
    }
