import sys
import pprint
import logging
import pathlib
from gladier import GladierBaseTool, generate_flow_definition


def make_corr_plots(
    corr_results: str,
    webplot_target_dir: str,
    webplot_extra_metadata: dict = None,
    corr_timing_output: dict = None,
    **data: dict,
):
    """
    Takes the corr results file and generates metadata and plots at a given location. Optionally
    allows for specifying extra metadata if desired.

    Generates a handful of files under the target dir, like: ``webplot_target_dir/corr_results/``
    These files consist of several plots plus a metadata.json file. This metadata.json file is updated
    with data within webplot_extra_metadata.

    :param corr_results: The output file generated by Corr. Raises an exception if this file does not
    exist or if the HDF file is bad.
    :param webplot_target_dir: Specifies where to generate the plots/metadata. Typically under a local
                               resources/ directory
    :param webplot_extra_metadata: Optional -- any additional metadata to include in the metadata file.
    
    """
    import os
    import json
    import time
    import pathlib
    from datetime import datetime
    from xpcs_webplot.plot_images import hdf2web_safe, XF, NpEncoder
    from xpcs_webplot import __version__ as webplot_version

    webplot_extra_metadata = webplot_extra_metadata or dict()
    corr_timing_output = corr_timing_output or dict()

    corr_start = time.time()
    webplot_output = hdf2web_safe(
        corr_results, target_dir=webplot_target_dir, image_only=True, overwrite=True
    )
    execution_time_seconds = round(time.time() - corr_start, 2)

    if webplot_output is None:
        raise Exception(
            "Plots failed to generate This is likely a problem with a bad input HDF "
            f"({corr_results})"
        )

    xf = XF(corr_results)
    metadata = xf.get_hdf_info()
    metadata["analysis_type"] = xf.atype
    metadata["start_time"] = xf.start_time
    metadata["plot_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    tools = webplot_extra_metadata.get('tools', [])
    tools += corr_timing_output.get("tools", [])
    tools += [
        {
            "name": "xpcs_webplot",
            "tool_version": str(webplot_version),
            "execution_time_seconds": execution_time_seconds,
            "device": "cpu",
            "source": "https://github.com/AZjk/xpcs_webplot",
        }
    ]
    metadata["tools"] = tools
    metadata.update(webplot_extra_metadata or {})
    save_dir = (
        pathlib.Path(webplot_target_dir)
        / f"{pathlib.Path(corr_results).stem}"
        / "metadata.json"
    )
    with open(save_dir, "w") as f:
        json.dump({"project_metadata": metadata}, f, indent=4, cls=NpEncoder)

    return {
        "images": [
            img for img in os.listdir(webplot_target_dir) if img.endswith(".png")
        ],
        "images_directory": str(webplot_target_dir),
        "input_hdf": corr_results,
        "webplot_output": webplot_output,
        "execution_time_seconds": execution_time_seconds,
    }


@generate_flow_definition(
    modifiers={
        "make_corr_plots": {"WaitTime": 604800, "ExceptionOnActionFailure": True}
    }
)
class MakeCorrPlots(GladierBaseTool):
    required_input = [
        "corr_results",
        "webplot_target_dir",
    ]

    compute_functions = [make_corr_plots]


if __name__ == "__main__":
    # This will pick up logging in the webplot tool
    logging.basicConfig(level=logging.INFO, handlers=[logging.StreamHandler()])
    if len(sys.argv) != 2:
        print("Usage: python plot.py my_file.hdf")
    input_file = pathlib.Path(sys.argv[1]).absolute()
    # Create the 'expected' processing directory, which should look like this:
    # * Top level webplot_target_dir/
    #     * HDF_Folder/
    #         * HDF_File.hdf
    corr_results = str(input_file)
    webplot_target_dir = str(
        input_file.parent / "output" / input_file.stem / "resources"
    )
    print(f"Plotting {corr_results} at location {webplot_target_dir}")
    output = make_corr_plots(
        corr_results=corr_results,
        webplot_target_dir=webplot_target_dir,
    )
    pprint.pprint(output)
