{
    'owner': '8idiuser', 
    'stages': {
            '01-Staging' : {'command': '/home/beams/8IDIUSER/DM_Workflows/xpcs8/start-xpcs8-remote-automate-02.sh $filePath $xpcsGroupName $sgeQueueName', 'outputVariableRegexList' : ['Cluster Data Directory: (?P<clusterDataDir>.*)', 'Cluster Results Directory: (?P<clusterResultsDir>.*)', 'Cluster JobLogs Directory: (?P<clusterJobLogsDir>.*)', 'Cluster JobErrorLogs Directory: (?P<clusterJobErrorLogsDir>.*)', 'Relative Data Directory: (?P<relativeDataDir>.*)', 'Input HDF5 File: (?P<inputHdf5File>.*)', 'Output HDF5 File: (?P<outputHdf5File>.*)', 'IMM File: (?P<immFile>.*)', 'SGE Job Name: (?P<sgeJobName>.*)', 'SGE Queue Name: (?P<sgeQueueName>.*)', 'File Data Directory: (?P<fileDataDir>.*)', 'User Data Directory: (?P<userDataDir>.*)', 'Cycle Data Directory: (?P<cycleDataDir>.*)', 'ORTHROS RESULTS DIR: (?P<ORTHROS_RESULTS_DIR>.*)', 'ORTHROS RESULTS LOGS RELATIVE DIR: (?P<ORTHROS_RESULTS_LOGS_RELATIVE_DIR>.*)', 'HADOOP FUSE DIR: (?P<HADOOP_FUSE_DIR>.*)', 'ID8I DATA ROOT: (?P<ID8I_DATA_ROOT>.*)', 'ID8I DATA ROOT NET: (?P<ID8I_DATA_ROOT_NET>.*)', 'ID8I GRIDFTP SERVER: (?P<ID8I_GRIDFTP_SERVER>.*)', 'CLUSTER GRIDFTP SERVER: (?P<CLUSTER_GRIDFTP_SERVER>.*)', 'HADOOP GRIDFTP SERVER: (?P<HADOOP_GRIDFTP_SERVER>.*)', 'XPCS Group Name: (?P<xpcsGroupName>.*)', 'ORTHROS DATA ROOT NFS: (?P<ORTHROS_DATA_ROOT_NFS>.*)', 'XPCS JOB FOLDER: (?P<XPCS_JOB_FOLDER>.*)', 'SOURCE ENDPOINT UUID: (?P<SOURCE_ENDPOINT_UUID>.*)', 'SOURCE ENDPOINT DATA ROOT: (?P<SOURCE_ENDPOINT_DATA_ROOT>.*)', 'ALCF Cluster Data Directory: (?P<ALCFclusterDataDir>.*)', 'ALCF Cluster Results Directory: (?P<ALCFclusterResultsDir>.*)']},
            '02-Automate' : {'command': 'ssh 8idiuser@amethyst "/home/beams/8IDIUSER/DM_Workflows/xpcs8/automate/automate_xpcs.py --endpoint $SOURCE_ENDPOINT_UUID --input $clusterResultsDir/$outputHdf5File --imm $clusterDataDir/$immFile"'},
            #'03-CopyBack' : {'command': 'globus-url-copy -r -cd -sync -sync-level 1 -fast -bs 2M -tcp-bs 2M -p 8 -cc 8 ftp://$CLUSTER_GRIDFTP_SERVER/$clusterResultsDir/../ALCF_results/$outputHdf5File ftp://$ID8I_GRIDFTP_SERVER/$ID8I_DATA_ROOT_NET/$cycleDataDir/$userDataDir/ALCF_results/'},
     },
    'description': 'XPCS8-04 Workflow Automate Post Processing', 
    'name': 'xpcs8-04-automate-PostProcess'
}